name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "3b6f163e86764b44bf366d4f3d19fda2" }
]

[triggers]
crons = [ ]
